/*
 *  Description: A thin, self-bootstrapping client for the newapi (new-api fork) admin API. newapi
 *               runs at a fixed address inside the compose bundle, so the ONLY configuration is a
 *               root password (generated by gen-env.sh). On first use the client initializes newapi
 *               if needed (POST /api/setup), logs in as root, and generates a system access token it
 *               then caches — no manual token/URL wiring. With that it mints a per-machine relay
 *               token, reveals its full key (this fork masks the key on list/get; only
 *               POST /api/token/{id}/key returns it un-masked), and deletes it on teardown.
 *
 *  Author(s):
 *      Nictheboy Li    <nictheboy@outlook.com>
 *
 */

package app.microteams.microcloud.machine.ai

import app.microteams.microcloud.common.config.MicroCloudConfig
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import java.net.CookieManager
import java.net.URI
import java.net.URLEncoder
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.nio.charset.StandardCharsets
import java.time.Duration
import org.rucca.cheese.common.error.BadRequestError
import org.springframework.stereotype.Component

@Component
class NewapiClient(private val config: MicroCloudConfig, private val objectMapper: ObjectMapper) {
    private val cfg
        get() = config.newapi

    @Volatile private var accessToken: String? = null
    private val lock = Any()

    /** True when the operator wired newapi (a root password is present). */
    fun isConfigured(): Boolean =
        !cfg.rootPassword.isNullOrBlank() && !cfg.adminBaseUrl.isNullOrBlank()

    /**
     * Ensure a relay token named [name] exists (mint it if absent) and return its newapi token id.
     * newapi's create doesn't return the id, so we look it up by the (unique) name afterwards.
     */
    fun ensureToken(name: String, quota: Long): Int {
        findTokenIdByName(name)?.let {
            return it
        }
        admin(
            "POST",
            "/api/token/",
            objectMapper.writeValueAsString(
                mapOf(
                    "name" to name,
                    "remain_quota" to quota,
                    "expired_time" to -1,
                    "unlimited_quota" to false,
                )
            ),
        )
        return findTokenIdByName(name)
            ?: throw BadRequestError("newapi token '$name' not found right after creation")
    }

    /** Reveal a token's full usable key (the only endpoint that returns it un-masked). */
    fun revealKey(tokenId: Int): String {
        val key = admin("POST", "/api/token/$tokenId/key", "").path("key").asText("")
        if (key.isBlank()) throw BadRequestError("newapi returned no key for token $tokenId")
        return key
    }

    /** Delete a relay token (teardown when the machine is removed). */
    fun deleteToken(tokenId: Int) {
        admin("DELETE", "/api/token/$tokenId", null)
    }

    private fun findTokenIdByName(name: String): Int? {
        val q = URLEncoder.encode(name, StandardCharsets.UTF_8)
        val data = admin("GET", "/api/token/search?keyword=$q", null)
        val items = if (data.isArray) data else data.path("items")
        return items.firstOrNull { it.path("name").asText() == name }?.path("id")?.asInt()
    }

    // ---- admin call with the cached access token, bootstrapping / re-auth on demand ----

    private fun admin(method: String, path: String, body: String?): JsonNode {
        val token = accessToken ?: bootstrap()
        val resp = adminRaw(method, path, body, token)
        if (resp.statusCode() == 401) {
            // token stale (e.g. newapi restarted) — drop it and re-bootstrap once.
            accessToken = null
            return objectMapper
                .readTree(checkOk(adminRaw(method, path, body, bootstrap())))
                .path("data")
        }
        return objectMapper.readTree(checkOk(resp)).path("data")
    }

    private fun adminRaw(
        method: String,
        path: String,
        body: String?,
        token: String,
    ): HttpResponse<String> {
        val base = cfg.adminBaseUrl!!.trimEnd('/')
        val b =
            HttpRequest.newBuilder()
                .uri(URI.create("$base$path"))
                .timeout(Duration.ofSeconds(30))
                .header("Authorization", "Bearer $token")
                .header("New-Api-User", ROOT_USER_ID.toString())
                .method(
                    method,
                    if (body == null) HttpRequest.BodyPublishers.noBody()
                    else HttpRequest.BodyPublishers.ofString(body),
                )
        if (body != null) b.header("Content-Type", "application/json")
        return try {
            newClient().send(b.build(), HttpResponse.BodyHandlers.ofString())
        } catch (e: Exception) {
            throw BadRequestError("newapi request failed: ${e.message}")
        }
    }

    private fun checkOk(resp: HttpResponse<String>): String {
        if (resp.statusCode() !in 200..299)
            throw BadRequestError("newapi ${resp.statusCode()} for admin call: ${resp.body()}")
        val json = objectMapper.readTree(resp.body())
        if (!json.path("success").asBoolean(true))
            throw BadRequestError("newapi error: ${json.path("message").asText()}")
        return resp.body()
    }

    /**
     * Initialize newapi if needed, log in as root, and generate a system access token — returning
     * (and caching) it. Uses a cookie-jar client because login authenticates via a session cookie.
     */
    private fun bootstrap(): String =
        synchronized(lock) {
            accessToken?.let {
                return it
            }
            val password =
                cfg.rootPassword?.takeIf { it.isNotBlank() }
                    ?: throw BadRequestError("microcloud.newapi.root-password is not set")
            val base =
                (cfg.adminBaseUrl ?: throw BadRequestError("newapi admin URL unset")).trimEnd('/')
            val client = newClient(CookieManager())

            // Initialize the root user on a fresh newapi (no-op if already set up).
            val setup = objectMapper.readTree(get(client, "$base/api/setup").body())
            if (!setup.path("data").path("status").asBoolean(false)) {
                post(
                    client,
                    "$base/api/setup",
                    objectMapper.writeValueAsString(
                        mapOf(
                            "username" to "root",
                            "password" to password,
                            "confirmPassword" to password,
                        )
                    ),
                )
            }
            // Log in (sets the session cookie), then generate + cache the access token.
            post(
                client,
                "$base/api/user/login",
                objectMapper.writeValueAsString(mapOf("username" to "root", "password" to password)),
            )
            val tokenResp =
                client.send(
                    HttpRequest.newBuilder(URI.create("$base/api/user/token"))
                        .header("New-Api-User", ROOT_USER_ID.toString())
                        .GET()
                        .build(),
                    HttpResponse.BodyHandlers.ofString(),
                )
            val token = objectMapper.readTree(checkOk(tokenResp)).path("data").asText("")
            if (token.isBlank()) throw BadRequestError("newapi did not return an access token")
            accessToken = token
            token
        }

    private fun get(client: HttpClient, url: String) =
        client.send(
            HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(15)).GET().build(),
            HttpResponse.BodyHandlers.ofString(),
        )

    private fun post(client: HttpClient, url: String, body: String) =
        client
            .send(
                HttpRequest.newBuilder(URI.create(url))
                    .timeout(Duration.ofSeconds(15))
                    .header("Content-Type", "application/json")
                    .header("New-Api-User", ROOT_USER_ID.toString())
                    .POST(HttpRequest.BodyPublishers.ofString(body))
                    .build(),
                HttpResponse.BodyHandlers.ofString(),
            )
            .also { checkOk(it) }

    private fun newClient(cookies: CookieManager? = null): HttpClient =
        HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(10))
            .apply { if (cookies != null) cookieHandler(cookies) }
            .build()

    private companion object {
        // newapi's root user is always id 1; the New-Api-User header must carry it.
        const val ROOT_USER_ID = 1
    }
}
