---------------------------------------------------------------------------
--                        DO NOT MODIFY THIS FILE                        --
--                                                                       --
-- The following content is generated by JPA according to entity classes --
---------------------------------------------------------------------------
CREATE
    SEQUENCE microcloud.account_ledger_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.account_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.audit_log_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.auth_secret_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.customer_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.ip_allocation_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.machine_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.machine_template_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.machine_type_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.network_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.offering_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.placement_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.proxmox_cluster_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.template_upload_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.tenant_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    SEQUENCE microcloud.zone_seq
START WITH
    1 INCREMENT BY 50;

CREATE
    TABLE
        microcloud.account(
            balance NUMERIC(
                20,
                6
            ) NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            customer_id BIGINT NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            tenant_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            name VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.account_ledger(
            amount NUMERIC(
                20,
                6
            ) NOT NULL,
            balance_after NUMERIC(
                20,
                6
            ) NOT NULL,
            balance_before NUMERIC(
                20,
                6
            ) NOT NULL,
            account_id BIGINT NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            tenant_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            remark VARCHAR(512),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.audit_log(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            secret_id BIGINT,
            tenant_id BIGINT,
            updated_at TIMESTAMP(6) NOT NULL,
            ACTION VARCHAR(512) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.auth_secret(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            tenant_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            secret_hash VARCHAR(64) NOT NULL,
            label VARCHAR(255),
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'REVOKED'
                )
            ),
            PRIMARY KEY(id),
            CONSTRAINT idx_secret_hash UNIQUE(secret_hash)
        );

CREATE
    TABLE
        microcloud.customer(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            tenant_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            external_ref VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'SUSPENDED'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.ip_allocation(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            machine_id BIGINT NOT NULL,
            network_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            ip VARCHAR(255) NOT NULL,
            PRIMARY KEY(id),
            CONSTRAINT idx_ip_alloc_net_ip UNIQUE(
                network_id,
                ip
            )
        );

CREATE
    TABLE
        microcloud.machine(
            cores INTEGER NOT NULL,
            disk_gb INTEGER NOT NULL,
            memory_mb INTEGER NOT NULL,
            vmid INTEGER,
            account_id BIGINT NOT NULL,
            api_key_id BIGINT,
            created_at TIMESTAMP(6) NOT NULL,
            customer_id BIGINT NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            network_id BIGINT NOT NULL,
            offering_id BIGINT NOT NULL,
            placement_id BIGINT NOT NULL,
            template_id BIGINT NOT NULL,
            tenant_id BIGINT NOT NULL,
            type_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            zone_id BIGINT,
            ssh_pubkey VARCHAR(4096),
            hostname VARCHAR(255) NOT NULL,
            ip VARCHAR(255),
            kind VARCHAR(255) CHECK(
                kind IN(
                    'LXC',
                    'VM'
                )
            ),
            login_user VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'PROVISIONING',
                    'STARTING',
                    'RUNNING',
                    'STOPPING',
                    'STOPPED',
                    'DELETING',
                    'DELETED',
                    'ERROR'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.machine_template(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            SOURCE VARCHAR(1024),
            description VARCHAR(255),
            kind VARCHAR(255) NOT NULL CHECK(
                kind IN(
                    'LXC',
                    'VM'
                )
            ),
            name VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'DISABLED'
                )
            ),
            PRIMARY KEY(id),
            CONSTRAINT idx_template_name UNIQUE(name)
        );

CREATE
    TABLE
        microcloud.machine_type(
            cores_max INTEGER NOT NULL,
            cores_min INTEGER NOT NULL,
            disk_gb_max INTEGER NOT NULL,
            disk_gb_min INTEGER NOT NULL,
            memory_mb_max INTEGER NOT NULL,
            memory_mb_min INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            description VARCHAR(255),
            name VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'DISABLED'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.machine_type_placement(
            machine_type_id BIGINT NOT NULL,
            placement_id BIGINT
        );

CREATE
    TABLE
        microcloud.network(
            prefix_length INTEGER NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            placement_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            bridge VARCHAR(255) NOT NULL,
            end_ip VARCHAR(255) NOT NULL,
            gateway VARCHAR(255) NOT NULL,
            name VARCHAR(255),
            start_ip VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'DISABLED'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.offering(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            machine_type_id BIGINT NOT NULL,
            template_id BIGINT NOT NULL,
            tenant_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            zone_id BIGINT NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'DISABLED'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.placement(
            cluster_id BIGINT NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            name VARCHAR(255) NOT NULL,
            node VARCHAR(255) NOT NULL,
            pool VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'DISABLED'
                )
            ),
            storage VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.proxmox_cluster(
            verify_tls BOOLEAN NOT NULL,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            api_url VARCHAR(255) NOT NULL,
            name VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'DISABLED'
                )
            ),
            token_id VARCHAR(255) NOT NULL,
            token_secret VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.template_upload(
            template_vmid INTEGER,
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            placement_id BIGINT NOT NULL,
            template_id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            job_log VARCHAR(4096),
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'PENDING',
                    'UPLOADING',
                    'DONE',
                    'ERROR'
                )
            ),
            volid VARCHAR(255),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.tenant(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            name VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'SUSPENDED'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.zone(
            created_at TIMESTAMP(6) NOT NULL,
            deleted_at TIMESTAMP(6),
            id BIGINT NOT NULL,
            updated_at TIMESTAMP(6) NOT NULL,
            description VARCHAR(255),
            name VARCHAR(255) NOT NULL,
            status VARCHAR(255) NOT NULL CHECK(
                status IN(
                    'ACTIVE',
                    'DISABLED'
                )
            ),
            PRIMARY KEY(id)
        );

CREATE
    TABLE
        microcloud.zone_placement(
            placement_id BIGINT,
            zone_id BIGINT NOT NULL
        );

CREATE
    INDEX IDX90cr1h1hr5sulrmvbqalwf6ak ON
    microcloud.account(tenant_id);

CREATE
    INDEX IDXq6ux6is14rkik374noo9xwo5 ON
    microcloud.account(customer_id);

CREATE
    INDEX IDXtcrtx2yww7sjdva7hckmuywtx ON
    microcloud.account_ledger(account_id);

CREATE
    INDEX IDXmcs7jul6ych8uff84db86qfuc ON
    microcloud.audit_log(tenant_id);

CREATE
    INDEX IDX8dneyq9dooaps5c35vah1nhmh ON
    microcloud.audit_log(secret_id);

CREATE
    INDEX IDXqqxtm4tdectmaol854uhmt9n1 ON
    microcloud.auth_secret(tenant_id);

CREATE
    INDEX IDXc76h3nyvfalawuonhr71y8e7b ON
    microcloud.customer(tenant_id);

CREATE
    INDEX IDX8gg4qkuxima5mysehpvtdklgy ON
    microcloud.customer(
        tenant_id,
        external_ref
    );

CREATE
    INDEX IDX8db694otgvdoixor1alex6yew ON
    microcloud.ip_allocation(machine_id);

CREATE
    INDEX IDXbnv7h3o9wtyjw4lgntglwln4e ON
    microcloud.machine(tenant_id);

CREATE
    INDEX IDXl599u4wq5p7ad3wee9fl89d92 ON
    microcloud.machine(
        tenant_id,
        customer_id
    );

CREATE
    INDEX IDXgibpxlfdrkuwm6mjmd0j0yb3v ON
    microcloud.machine_type(name);

CREATE
    INDEX IDXjpu0rri02kfnjio2cxhf90co7 ON
    microcloud.network(placement_id);

CREATE
    INDEX IDXgkorh0ddqbw1lxxd98tqx1p53 ON
    microcloud.offering(tenant_id);

CREATE
    INDEX IDX7gvbibau6piqp7hi3ucyj3b9b ON
    microcloud.placement(cluster_id);

CREATE
    INDEX IDXpioo108jvytvpkm6c9dj2gnl3 ON
    microcloud.placement(name);

CREATE
    INDEX IDXpoa1g615whm86vkt28opxo11x ON
    microcloud.proxmox_cluster(name);

CREATE
    INDEX IDXnr8jsp0roxtskkvkhvk9gl0ft ON
    microcloud.template_upload(
        template_id,
        placement_id
    );

CREATE
    INDEX IDXdcxf3ksi0gyn1tieeq0id96lm ON
    microcloud.tenant(name);

CREATE
    INDEX IDX27s7q3vqft9a76yi9k7e7rroi ON
    microcloud.zone(name);

ALTER TABLE
    IF EXISTS microcloud.machine_type_placement ADD CONSTRAINT FKer8yv0n6u52s50xsyf7ycyur7 FOREIGN KEY(machine_type_id) REFERENCES microcloud.machine_type;

ALTER TABLE
    IF EXISTS microcloud.zone_placement ADD CONSTRAINT FKemu3ulf5avs3wxg6e6fu468fh FOREIGN KEY(zone_id) REFERENCES microcloud.zone;
