#!/usr/bin/env bash
#
# Generate the .env docker-compose reads its secrets from: a random DB password and the JWT secret
# the backend signs/verifies its tokens with. Run this once, before `docker compose up -d`.
#
set -euo pipefail
cd "$(dirname "$0")"

if [ -f .env ]; then
    echo "refusing to overwrite an existing .env (delete it yourself to regenerate secrets)" >&2
    exit 1
fi

# No openssl dependency: draw from /dev/urandom and keep only URL/JSON-safe characters.
secret() { (set +o pipefail; LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"); }

# The port the gateway listens on, and this host's primary IP — used to build the URL a provisioned
# machine (outside the compose network) uses to reach newapi through the gateway. Auto-detected;
# override NEWAPI_MACHINE_BASE_URL below if the guess is wrong (e.g. behind NAT / a public domain).
NGINX_PORT=80
HOST_IP=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')
[ -n "$HOST_IP" ] || HOST_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
[ -n "$HOST_IP" ] || HOST_IP=127.0.0.1

cat > .env <<EOF
# Generated by gen-env.sh — contains secrets. Never commit or share. Keep it next to
# docker-compose.yml. Regenerating invalidates every existing login (the JWT secret changes).
POSTGRES_USER=microcloud
POSTGRES_DB=microcloud
POSTGRES_PASSWORD=$(secret 40)
JWT_SECRET=$(secret 64)
# The platform operator's login password (super-admin). Read it back from this file to log in.
SUPERADMIN_PASSWORD=$(secret 24)

# Host port the gateway (nginx) listens on. Put your TLS-terminating reverse proxy in front of it.
NGINX_HTTP_PORT=$NGINX_PORT

# newapi (the default AI relay). The backend initializes newapi with this root password on first
# use and mints per-machine relay tokens — no other newapi wiring needed. NEWAPI_MACHINE_BASE_URL is
# what a machine's Claude Code points ANTHROPIC_BASE_URL at (newapi reached through the gateway,
# since machines are off the compose network); auto-guessed from this host's IP — override if wrong.
NEWAPI_ROOT_PASSWORD=$(secret 24)
NEWAPI_MACHINE_BASE_URL=http://$HOST_IP:$NGINX_PORT/newapi
EOF
chmod 600 .env

mkdir -p app_data/postgresql app_data/newapi keys

# The operator SSH keypair used for provisioning: the backend injects the PUBLIC key into each new
# container (as root) and uses the PRIVATE key to SSH in and run init-machine.py. Generated here so
# provisioning needs no manual configuration; ./keys is mounted read-only at /keys in the backend.
if [ ! -f keys/operator ]; then
    ssh-keygen -t ed25519 -N '' -C microcloud-operator -f keys/operator >/dev/null
    echo "Generated operator provisioning keypair at ./keys/operator(.pub)."
fi

echo "Wrote .env (chmod 600) and created app_data/ + keys/ directories."
echo "Next: docker compose up -d   then   docker compose ps   (wait for every service 'healthy')."
