/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.microcloud.api

import app.microteams.microcloud.model.AccountDTO
import app.microteams.microcloud.model.CreateAccountRequestDTO
import app.microteams.microcloud.model.ErrorDTO
import app.microteams.microcloud.model.ListAccountLedgerResponseDTO
import app.microteams.microcloud.model.ListAccountsResponseDTO
import app.microteams.microcloud.model.TopupAccountRequestDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface AccountApi {

    @Operation(
        tags = ["account"],
        summary = "Create a fund account for a customer",
        operationId = "createAccount",
        description =
            """Open a prepaid fund account under one of the tenant's customers. Generic ledger: pure numeric balance, no unit.""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/account"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createAccount(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createAccountRequestDTO: CreateAccountRequestDTO
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "",
        operationId = "getAccount",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/account/{id}"],
        produces = ["application/json"],
    )
    fun getAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "List an account's ledger (every balance change; charges, top-ups, daily grants)",
        operationId = "listAccountLedger",
        description =
            """The account's full change history (top-ups / charges / …), newest-scan paginated.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(implementation = ListAccountLedgerResponseDTO::class)
                            )
                        ],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/account/{id}/ledger"],
        produces = ["application/json"],
    )
    fun listAccountLedger(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListAccountLedgerResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "List accounts (optionally for one customer)",
        operationId = "listAccounts",
        description =
            """List fund accounts. Optional customer_id filter — but it MUST reference a customer that belongs to the calling tenant, else the call is rejected.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListAccountsResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/account"],
        produces = ["application/json"],
    )
    fun listAccounts(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "customer_id", required = false)
        customerId: kotlin.Long?,
    ): ResponseEntity<ListAccountsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["account"],
        summary = "Add funds to an account (returns the updated account)",
        operationId = "topupAccount",
        description =
            """Add funds to an account (positive amount). Recorded as one immutable ledger entry.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = AccountDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/account/{id}/topup"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun topupAccount(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        topupAccountRequestDTO: TopupAccountRequestDTO,
    ): ResponseEntity<AccountDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
