/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.microcloud.api

import app.microteams.microcloud.model.CreateCustomerRequestDTO
import app.microteams.microcloud.model.CustomerDTO
import app.microteams.microcloud.model.ErrorDTO
import app.microteams.microcloud.model.ListCustomersResponseDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface CustomerApi {

    @Operation(
        tags = ["customer"],
        summary = "Create a customer",
        operationId = "createCustomer",
        description =
            """Register one of the tenant's end-users (keyed by externalRef, the tenant's own user id).""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = CustomerDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/customer"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createCustomer(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createCustomerRequestDTO: CreateCustomerRequestDTO
    ): ResponseEntity<CustomerDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["customer"],
        summary = "Delete a customer (must have no machines or accounts)",
        operationId = "deleteCustomer",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/customer/{id}"],
        produces = ["application/json"],
    )
    fun deleteCustomer(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["customer"],
        summary = "",
        operationId = "getCustomer",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = CustomerDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/customer/{id}"],
        produces = ["application/json"],
    )
    fun getCustomer(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<CustomerDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["customer"],
        summary = "List the tenant's customers",
        operationId = "listCustomers",
        description =
            """List this tenant's customers. Enumeration = composable optional filters, but the tenant-scope condition is ALWAYS enforced: you only ever see your own customers.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListCustomersResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/customer"],
        produces = ["application/json"],
    )
    fun listCustomers(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "external_ref", required = false)
        externalRef: kotlin.String?,
    ): ResponseEntity<ListCustomersResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
