/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.microcloud.api

import app.microteams.microcloud.model.CreateMachineRequestDTO
import app.microteams.microcloud.model.CreateMachineTypeRequestDTO
import app.microteams.microcloud.model.CreateNetworkRequestDTO
import app.microteams.microcloud.model.CreateOfferingRequestDTO
import app.microteams.microcloud.model.CreatePlacementRequestDTO
import app.microteams.microcloud.model.CreateProxmoxClusterRequestDTO
import app.microteams.microcloud.model.CreateZoneRequestDTO
import app.microteams.microcloud.model.ErrorDTO
import app.microteams.microcloud.model.ListMachineTemplatesResponseDTO
import app.microteams.microcloud.model.ListMachineTypesResponseDTO
import app.microteams.microcloud.model.ListMachinesResponseDTO
import app.microteams.microcloud.model.ListNetworksResponseDTO
import app.microteams.microcloud.model.ListOfferingsResponseDTO
import app.microteams.microcloud.model.ListPlacementsResponseDTO
import app.microteams.microcloud.model.ListProxmoxClustersResponseDTO
import app.microteams.microcloud.model.ListTemplateUploadsResponseDTO
import app.microteams.microcloud.model.ListZonesResponseDTO
import app.microteams.microcloud.model.MachineDTO
import app.microteams.microcloud.model.MachineTypeDTO
import app.microteams.microcloud.model.NetworkDTO
import app.microteams.microcloud.model.OfferingDTO
import app.microteams.microcloud.model.PlacementDTO
import app.microteams.microcloud.model.ProxmoxClusterDTO
import app.microteams.microcloud.model.ProxmoxInventoryDTO
import app.microteams.microcloud.model.TemplateUploadDTO
import app.microteams.microcloud.model.UpdateMachineTypeRequestDTO
import app.microteams.microcloud.model.UpdateNetworkRequestDTO
import app.microteams.microcloud.model.UpdateOfferingRequestDTO
import app.microteams.microcloud.model.UpdatePlacementRequestDTO
import app.microteams.microcloud.model.UpdateProxmoxClusterRequestDTO
import app.microteams.microcloud.model.UpdateZoneRequestDTO
import app.microteams.microcloud.model.UploadTemplateRequestDTO
import app.microteams.microcloud.model.ZoneDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface MachineApi {

    @Operation(
        tags = ["machine"],
        summary =
            "Provision a machine (pick a type, zone, template, and a spec within the type's ranges)",
        operationId = "createMachine",
        description =
            """Provision a machine from an OFFERING (which fixes machine type + zone + template) plus a hostname, a spec within the offering type's ranges, a login user + SSH key, and the fund account to charge. ASYNC: returns 201 with status 'provisioning'; the CT is created on Proxmox in the background — poll GET /machine/{id} until 'running' or 'error'. MicroCloud auto-selects the placement (backing the type, in the zone, with the template uploaded, with a free IP) and leases the private IP.""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created (provisioning has started; poll for status)",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createMachine(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createMachineRequestDTO: CreateMachineRequestDTO
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Create a machine type",
        operationId = "createMachineType",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = MachineTypeDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/type"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createMachineType(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createMachineTypeRequestDTO: CreateMachineTypeRequestDTO
    ): ResponseEntity<MachineTypeDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Add a network segment bound to a placement",
        operationId = "createNetwork",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = NetworkDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/network"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createNetwork(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createNetworkRequestDTO: CreateNetworkRequestDTO
    ): ResponseEntity<NetworkDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Grant a tenant a (machine type, zone, network) triple",
        operationId = "createOffering",
        description =
            """Grant a tenant a (machine type, zone, template) triple. Validates the three exist AND that the type and zone share at least one placement (else no machine from it could ever land).""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = OfferingDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/offering"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createOffering(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createOfferingRequestDTO: CreateOfferingRequestDTO
    ): ResponseEntity<OfferingDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Register a placement",
        operationId = "createPlacement",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = PlacementDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/placement"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createPlacement(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createPlacementRequestDTO: CreatePlacementRequestDTO
    ): ResponseEntity<PlacementDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["proxmox"],
        summary = "Add a Proxmox cluster (endpoint + API token)",
        operationId = "createProxmoxCluster",
        description =
            """Register a Proxmox provider credential. tokenSecret is WRITE-ONLY — it is stored for runtime use and never returned by any read.""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = ProxmoxClusterDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/proxmox"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createProxmoxCluster(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createProxmoxClusterRequestDTO: CreateProxmoxClusterRequestDTO
    ): ResponseEntity<ProxmoxClusterDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Create a zone",
        operationId = "createZone",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = ZoneDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/zone"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createZone(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createZoneRequestDTO: CreateZoneRequestDTO
    ): ResponseEntity<ZoneDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Destroy a machine (async; the Proxmox CT is torn down in the background)",
        operationId = "deleteMachine",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "202",
                    description =
                        "Accepted — deletion started (status becomes 'deleting'); poll GET until it 404s",
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/machine/{id}"],
        produces = ["application/json"],
    )
    fun deleteMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "deleteMachineType",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/machine/type/{id}"],
        produces = ["application/json"],
    )
    fun deleteMachineType(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "deleteNetwork",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/machine/network/{id}"],
        produces = ["application/json"],
    )
    fun deleteNetwork(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "deleteOffering",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/machine/offering/{id}"],
        produces = ["application/json"],
    )
    fun deleteOffering(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "deletePlacement",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/machine/placement/{id}"],
        produces = ["application/json"],
    )
    fun deletePlacement(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["proxmox"],
        summary = "Remove a Proxmox cluster (must be unused by placements)",
        operationId = "deleteProxmoxCluster",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/machine/proxmox/{id}"],
        produces = ["application/json"],
    )
    fun deleteProxmoxCluster(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "deleteZone",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/machine/zone/{id}"],
        produces = ["application/json"],
    )
    fun deleteZone(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "getMachine",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/{id}"],
        produces = ["application/json"],
    )
    fun getMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "getMachineType",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = MachineTypeDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/type/{id}"],
        produces = ["application/json"],
    )
    fun getMachineType(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<MachineTypeDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "getNetwork",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = NetworkDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/network/{id}"],
        produces = ["application/json"],
    )
    fun getNetwork(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<NetworkDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "getOffering",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = OfferingDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/offering/{id}"],
        produces = ["application/json"],
    )
    fun getOffering(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<OfferingDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "getPlacement",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = PlacementDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/placement/{id}"],
        produces = ["application/json"],
    )
    fun getPlacement(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<PlacementDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["proxmox"],
        summary = "Get a Proxmox cluster",
        operationId = "getProxmoxCluster",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = ProxmoxClusterDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/proxmox/{id}"],
        produces = ["application/json"],
    )
    fun getProxmoxCluster(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<ProxmoxClusterDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["proxmox"],
        summary =
            "Live inventory read from the cluster (nodes / pools / storages / bridges) to help configure placements",
        operationId = "getProxmoxInventory",
        description =
            """Live read from the cluster (nodes / pools / storages / bridges) to help an operator pick placement coordinates. Not stored.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ProxmoxInventoryDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/proxmox/{id}/inventory"],
        produces = ["application/json"],
    )
    fun getProxmoxInventory(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<ProxmoxInventoryDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "getZone",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = ZoneDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/zone/{id}"],
        produces = ["application/json"],
    )
    fun getZone(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<ZoneDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "List available machine templates (built at build time; list-only)",
        operationId = "listMachineTemplates",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(implementation = ListMachineTemplatesResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/template"],
        produces = ["application/json"],
    )
    fun listMachineTemplates(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListMachineTemplatesResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "List machine types (tenant-visible; performance class + allowed spec ranges)",
        operationId = "listMachineTypes",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = ListMachineTypesResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/type"],
        produces = ["application/json"],
    )
    fun listMachineTypes(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListMachineTypesResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "List machines (optionally for one customer)",
        operationId = "listMachines",
        description =
            """List the tenant's machines. Optional customer_id filter must reference the tenant's own customer.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListMachinesResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine"],
        produces = ["application/json"],
    )
    fun listMachines(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "customer_id", required = false)
        customerId: kotlin.Long?,
    ): ResponseEntity<ListMachinesResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "List network segments (an IP range bound to a placement)",
        operationId = "listNetworks",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListNetworksResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/network"],
        produces = ["application/json"],
    )
    fun listNetworks(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(description = "")
        @Valid
        @RequestParam(value = "placement_id", required = false)
        placementId: kotlin.Long?,
    ): ResponseEntity<ListNetworksResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary =
            "List offerings — super-admin sees all (optionally by tenant_id); a tenant sees its own, each carrying the machine type spec ranges, zone, and template it needs",
        operationId = "listOfferings",
        description =
            """DUAL-REALM. Super-admin: all offerings, or filter by tenant_id. Tenant: only its own (the tenant_id query is ignored). Each row embeds the machine type's spec ranges + zone/template names, so a tenant needs no other catalog lookups.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListOfferingsResponseDTO::class))],
                )
            ],
        security =
            [SecurityRequirement(name = "tenantSecret"), SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/offering"],
        produces = ["application/json"],
    )
    fun listOfferings(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
        @Parameter(
            description = "super-admin only; ignored for a tenant (which always sees its own)"
        )
        @Valid
        @RequestParam(value = "tenant_id", required = false)
        tenantId: kotlin.Long?,
    ): ResponseEntity<ListOfferingsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "List placements (a cluster+node+pool+storage coordinate)",
        operationId = "listPlacements",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema = Schema(implementation = ListPlacementsResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/placement"],
        produces = ["application/json"],
    )
    fun listPlacements(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListPlacementsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["proxmox"],
        summary = "List configured Proxmox clusters",
        operationId = "listProxmoxClusters",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(implementation = ListProxmoxClustersResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/proxmox"],
        produces = ["application/json"],
    )
    fun listProxmoxClusters(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListProxmoxClustersResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Per-placement upload status of a template",
        operationId = "listTemplateUploads",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(implementation = ListTemplateUploadsResponseDTO::class)
                            )
                        ],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/template/{id}/upload"],
        produces = ["application/json"],
    )
    fun listTemplateUploads(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<ListTemplateUploadsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "List zones (tenant-visible locality partitions)",
        operationId = "listZones",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListZonesResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/machine/zone"],
        produces = ["application/json"],
    )
    fun listZones(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListZonesResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Start a stopped machine (async; poll for status)",
        operationId = "startMachine",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "202",
                    description =
                        "Accepted — start requested (status 'starting'); poll GET for 'running'",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/{id}/start"],
        produces = ["application/json"],
    )
    fun startMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Stop a running machine (async; does not destroy it)",
        operationId = "stopMachine",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "202",
                    description =
                        "Accepted — stop requested (status 'stopping'); poll GET for 'stopped'",
                    content = [Content(schema = Schema(implementation = MachineDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "tenantSecret")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/{id}/stop"],
        produces = ["application/json"],
    )
    fun stopMachine(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<MachineDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "updateMachineType",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = MachineTypeDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/machine/type/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateMachineType(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateMachineTypeRequestDTO: UpdateMachineTypeRequestDTO,
    ): ResponseEntity<MachineTypeDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "updateNetwork",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = NetworkDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/machine/network/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateNetwork(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateNetworkRequestDTO: UpdateNetworkRequestDTO,
    ): ResponseEntity<NetworkDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Enable/disable an offering",
        operationId = "updateOffering",
        description =
            """Enable or disable an offering. A disabled offering can't be used to create machines.""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = OfferingDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/machine/offering/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateOffering(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateOfferingRequestDTO: UpdateOfferingRequestDTO,
    ): ResponseEntity<OfferingDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "updatePlacement",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = PlacementDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/machine/placement/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updatePlacement(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updatePlacementRequestDTO: UpdatePlacementRequestDTO,
    ): ResponseEntity<PlacementDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["proxmox"],
        summary = "Update a Proxmox cluster (rotate token, enable/disable)",
        operationId = "updateProxmoxCluster",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = ProxmoxClusterDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/machine/proxmox/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateProxmoxCluster(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateProxmoxClusterRequestDTO: UpdateProxmoxClusterRequestDTO,
    ): ResponseEntity<ProxmoxClusterDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "",
        operationId = "updateZone",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = ZoneDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/machine/zone/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateZone(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateZoneRequestDTO: UpdateZoneRequestDTO,
    ): ResponseEntity<ZoneDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["machine"],
        summary = "Upload/refresh the template image to a placement's storage (async; poll status)",
        operationId = "uploadTemplate",
        description =
            """Copy the template image onto a placement's storage. ASYNC: returns 202; poll GET /machine/template/{id}/upload for per-placement status until 'done'. A machine can only be created on a placement where its template is 'done'.""",
        responses =
            [
                ApiResponse(
                    responseCode = "202",
                    description = "Accepted",
                    content = [Content(schema = Schema(implementation = TemplateUploadDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/machine/template/{id}/upload"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun uploadTemplate(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        uploadTemplateRequestDTO: UploadTemplateRequestDTO,
    ): ResponseEntity<TemplateUploadDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
