/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.10.0). https://openapi-generator.tech Do not edit the class manually.
 */
package app.microteams.microcloud.api

import app.microteams.microcloud.model.CreateTenantRequestDTO
import app.microteams.microcloud.model.CreateTenantSecretRequestDTO
import app.microteams.microcloud.model.CreateTenantSecretResponseDTO
import app.microteams.microcloud.model.ErrorDTO
import app.microteams.microcloud.model.ListTenantSecretsResponseDTO
import app.microteams.microcloud.model.ListTenantsResponseDTO
import app.microteams.microcloud.model.TenantDTO
import app.microteams.microcloud.model.UpdateTenantRequestDTO
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import javax.validation.Valid
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@RestController
@Validated
interface TenantApi {

    @Operation(
        tags = ["tenant"],
        summary = "Create a tenant",
        operationId = "createTenant",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content = [Content(schema = Schema(implementation = TenantDTO::class))],
                ),
                ApiResponse(
                    responseCode = "400",
                    description = "Bad Request",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/tenant"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createTenant(
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createTenantRequestDTO: CreateTenantRequestDTO
    ): ResponseEntity<TenantDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Mint a new auth secret (plaintext value returned ONCE)",
        operationId = "createTenantSecret",
        description =
            """Mint a new auth secret for the tenant. The plaintext value is returned ONCE (only its hash is stored); the tenant uses it as a Bearer token.""",
        responses =
            [
                ApiResponse(
                    responseCode = "201",
                    description = "Created",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(implementation = CreateTenantSecretResponseDTO::class)
                            )
                        ],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.POST],
        value = ["/tenant/{id}/secret"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun createTenantSecret(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        createTenantSecretRequestDTO: CreateTenantSecretRequestDTO,
    ): ResponseEntity<CreateTenantSecretResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Delete a tenant (must have no customers)",
        operationId = "deleteTenant",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/tenant/{id}"],
        produces = ["application/json"],
    )
    fun deleteTenant(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Get a tenant",
        operationId = "getTenant",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = TenantDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/tenant/{id}"],
        produces = ["application/json"],
    )
    fun getTenant(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long
    ): ResponseEntity<TenantDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "List a tenant's auth secrets (metadata only; never the value)",
        operationId = "listTenantSecrets",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [
                            Content(
                                schema =
                                    Schema(implementation = ListTenantSecretsResponseDTO::class)
                            )
                        ],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/tenant/{id}/secret"],
        produces = ["application/json"],
    )
    fun listTenantSecrets(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListTenantSecretsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "List tenants",
        operationId = "listTenants",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content =
                        [Content(schema = Schema(implementation = ListTenantsResponseDTO::class))],
                )
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/tenant"],
        produces = ["application/json"],
    )
    fun listTenants(
        @Parameter(description = "cursor — id of the first item to return")
        @Valid
        @RequestParam(value = "page_start", required = false)
        pageStart: kotlin.Long?,
        @Parameter(description = "", schema = Schema(defaultValue = "20"))
        @Valid
        @RequestParam(value = "page_size", required = false, defaultValue = "20")
        pageSize: kotlin.Int,
    ): ResponseEntity<ListTenantsResponseDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Revoke a tenant auth secret",
        operationId = "revokeTenantSecret",
        description = """""",
        responses =
            [
                ApiResponse(responseCode = "204", description = "No Content"),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.DELETE],
        value = ["/tenant/{id}/secret/{secretId}"],
        produces = ["application/json"],
    )
    fun revokeTenantSecret(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @PathVariable("secretId")
        secretId: kotlin.Long,
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["tenant"],
        summary = "Update a tenant (rename, enable/disable)",
        operationId = "updateTenant",
        description = """""",
        responses =
            [
                ApiResponse(
                    responseCode = "200",
                    description = "OK",
                    content = [Content(schema = Schema(implementation = TenantDTO::class))],
                ),
                ApiResponse(
                    responseCode = "404",
                    description = "Not Found",
                    content = [Content(schema = Schema(implementation = ErrorDTO::class))],
                ),
            ],
        security = [SecurityRequirement(name = "superAdmin")],
    )
    @RequestMapping(
        method = [RequestMethod.PATCH],
        value = ["/tenant/{id}"],
        produces = ["application/json"],
        consumes = ["application/json"],
    )
    fun updateTenant(
        @Parameter(description = "", required = true) @PathVariable("id") id: kotlin.Long,
        @Parameter(description = "", required = true)
        @Valid
        @RequestBody
        updateTenantRequestDTO: UpdateTenantRequestDTO,
    ): ResponseEntity<TenantDTO> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
